spring:
  application:
    name: resolve

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

server:
  servlet:
    encoding: # http 요청 시 인코딩 설정
      charset: UTF-8
      enabled: true
      force: true
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:resolve
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  data:
    web:
      pageable:
        one-indexed-parameters: true  # web 요청이 왔을 경우 페이지번호를 보정해주는 옵션
        default-page-size: 5

  h2:
    console:
      enabled: true
      path: /h2-console
